node {

    withMaven(maven:'M3') {

        stage('Checkout') {
            git url: 'https://github.com/xjr100419/microservices-netflix-sample.git', credentialsId: 'github-piomin', branch: 'master'
        }

        stage('Build') {
            dir ('eureka-server') {
                sh 'mvn clean install'

                def pom = readMavenPom file:'pom.xml'
                print pom.version
                env.version = pom.version
            }
        }

        stage('Image') {
            dir ('eureka-server') {
                def app = docker.build "192.168.80.180:5000/demo/eureka-server:${env.version}"
                app.push()
            }
        }



        stage ('Deploy') {
            sh "kubectl apply -f kubernetes/deployment.yml"
            sh "kubectl apply -f kubernetes/svc.yml"
        }

    }

}