node {

    withMaven(maven:'M3') {

        stage('Checkout') {
            git url: 'https://github.com/xjr100419/microservices-netflix-sample.git', credentialsId: 'github-piomin', branch: 'master'
        }

        stage('Build') {
            dir ('eureka-server') {
                sh 'mvn clean install'

                def pom = readMavenPom file:'pom.xml'
                print pom.version
                env.version = pom.version


                tag = pom.version
                    appName = "eureka-server"
                    registryHost = "192.168.80.180:5000/demo/"
                    imageName = "${registryHost}${appName}:${tag}"
                    env.BUILDIMG=imageName
            }
        }

        stage('Image') {
            dir ('eureka-server') {
                def app = docker.build "${imageName}"
                app.push()
            }
        }



        stage ('Deploy') {
            dir ('eureka-server') {
                sh "sed 's#192.168.80.180:5000/demo/eureka-server:latest#'$BUILDIMG'#' kubernetes/deployment.yml | kubectl apply -f -"

                sh "kubectl apply -f kubernetes/svc.yml"
            }
        }

    }

}