apiVersion: v1
kind: Service
metadata: 
  name: hystrix-service
  namespace: default
spec:
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 8090
  selector: 
    app: hystrix
  type: NodePort