apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: edge
  name: edge
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: edge
    spec:
      containers:
        -
          image: 192.168.80.180:5000/demo/edge:latest
          name: edge
          ports:
            -
              containerPort: 8080
          env:
            - name: EUREKA_URL
              value: http://eureka-service.default.svc.cluster.local:8761/eureka
