zuul:
  routes:
    contacts-service:
      path: /account/**
      stripPrefix: true
      serviceId: account-service

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${random.int}
    preferIpAddress: false

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
---

spring:
  profiles: docker

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${random.int}
    preferIpAddress: false
