apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: eureka
  name: eureka
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        -
          image: 192.168.80.180:5000/demo/eureka-server:latest
          name: eureka
          ports:
            -
              containerPort: 8761
