apiVersion: v1
kind: Service
metadata: 
  name: eureka-service
  namespace: default
spec:
  externalIPs:
      - 192.168.80.186
  ports: 
    - 
      port: 8761
      targetPort: 8761
  selector: 
    app: eureka
  type: LoadBalancer